package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

// The .deb's copyright file, /usr/share/doc/wopr/copyright, in Debian's machine-readable format
// (https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/). Debian Policy §12.5 asks
// for every licence in full, where the sources came from and how to reach upstream. Nothing in
// it is typed twice: wopr's licence comes from LICENSE; the third-party text and art, and their
// terms, from NOTICE.md; which files quote the film, from the provenance tags in the Go source
// (internal/script); and each linked module's licence from the module itself, matched against
// the licence texts it is filed under, so that a module under any other licence stops the tool.

const (
	repoURL    = "https://github.com/GhostofGoes/WOPR"
	dep5Format = "https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"
)

// The provenance tags of text that wopr's licence does not cover, as Go code outside package
// script spells them.
var (
	filmTag = regexp.MustCompile(`\bscript\.(Film|Recon|Reconstructed)\b`)
	abs0Tag = regexp.MustCompile(`\bscript\.ABS0\b`)
	mapTag  = regexp.MustCompile(`\bscript\.MatthewThomasMap\b`)
)

// filmOutsideCode are the files outside the Go source that quote or show the film's screen text
// (AGENTS.md, "Takedown runbook"). Each pattern must match something, so the list cannot go stale
// unnoticed.
var filmOutsideCode = []string{
	"docs/man/wopr.6",
	"docs/screenshots/*",
	"site/content/*",
	"site/data/games/*",
	"site/static/img/*",
}

const disclaimer = `wopr is a fan-made homage to the 1983 film WarGames. It quotes short
passages of the text that the film shows on the WOPR computer's terminal.
Those quotations remain the property of their copyright holders and are not
licensed under the Expat (MIT) licence; the files that hold them are listed
below with a comment that says so. This project is not affiliated with,
endorsed by, or sponsored by Metro-Goldwyn-Mayer, United Artists, or anyone
involved in making the film. NOTICE.md says more; the package installs it
beside this file.`

const headerComment = `Generated by "go run ./internal/tools/notices" from LICENSE, NOTICE.md,
the provenance tags in the source and the Go modules' licences; do not edit
it by hand. The program is statically linked. Each Files paragraph whose
pattern starts with a Go module path (std is the Go standard library and
runtime) covers the code linked in from that module. "wopr --licenses"
prints those licences exactly as each module ships them.`

const filmComment = `Besides code, these files quote the film's screen text, which the Expat
licence does not cover (see the Disclaimer).`

const docsComment = `The manual page, screenshots of the program, and the pages and
screenshots of the documentation site. They quote or show the film's screen
text (see the Disclaimer), and the pictures of Global Thermonuclear War's big
board show Matthew Thomas's map (see internal/assets/gtwmap.go).`

const abs0Comment = `These files quote the film's screen text (the backdoor connection
header, the closing montage's scenario names) as the abs0/wargames project
transcribed it: https://github.com/abs0/wargames, wargames.sh, commit
010ed92. The BSD-2-clause licence covers the transcription; the text itself
is the film's, which no licence here covers (see the Disclaimer).`

const mapComment = `The big board's world map in Global Thermonuclear War is Matthew
Thomas's ASCII world map, from https://asciiart.website/art/3719,
reproduced exactly as he drew it, under the terms he gave with it.`

// licence is a licence text filed under a DEP-5 short name.
type licence struct {
	name, text string
}

// paragraph is a DEP-5 Files paragraph.
type paragraph struct {
	files     []string
	copyright []string
	licence   string
	comment   string
}

// renderCopyright writes the copyright file for a source tree at root, the Go toolchain at
// goroot, and the modules linked into the Linux builds.
func renderCopyright(root, goroot, goversion string, mods map[string]module) ([]byte, error) {
	own, err := readLicence(filepath.Join(root, "LICENSE"))
	if err != nil {
		return nil, err
	}
	golang, err := readLicence(filepath.Join(goroot, "LICENSE"))
	if err != nil {
		return nil, fmt.Errorf("the Go licence: %w", err)
	}
	notice, err := os.ReadFile(filepath.Join(root, "NOTICE.md"))
	if err != nil {
		return nil, err
	}
	abs0, mapTerms, err := noticeTexts(string(notice))
	if err != nil {
		return nil, fmt.Errorf("NOTICE.md: %w", err)
	}
	film, abs0Files, mapFiles, err := taggedFiles(root)
	if err != nil {
		return nil, err
	}
	for _, p := range filmOutsideCode {
		if m, _ := filepath.Glob(filepath.Join(root, filepath.FromSlash(p))); len(m) == 0 {
			return nil, fmt.Errorf("%s matches no file; update filmOutsideCode", p)
		}
	}

	expat := licence{"Expat", own.text}
	bsd3 := licence{"BSD-3-clause", golang.text}
	bsd2 := licence{"BSD-2-clause", abs0.text}
	mapLicence := licence{"Matthew-Thomas-map", mapTerms.text}
	filed := []licence{expat, bsd3} // what a module's licence may be

	paras := []paragraph{{files: []string{"*"}, copyright: own.holders, licence: expat.name}}
	filmOnly := slices.DeleteFunc(slices.Clone(film), func(f string) bool {
		return slices.Contains(abs0Files, f) || slices.Contains(mapFiles, f)
	})
	if len(filmOnly) > 0 {
		paras = append(paras, paragraph{filmOnly, own.holders, expat.name, filmComment})
	}
	paras = append(paras, paragraph{filmOutsideCode, own.holders, expat.name, docsComment})
	if len(abs0Files) > 0 {
		paras = append(paras, paragraph{
			abs0Files, append(slices.Clone(own.holders), abs0.holders...),
			expat.name + " and " + bsd2.name, abs0Comment,
		})
	}
	if len(mapFiles) > 0 {
		paras = append(paras, paragraph{
			mapFiles, append(slices.Clone(own.holders), mapTerms.holders...),
			expat.name + " and " + mapLicence.name, mapComment,
		})
	}
	paras = append(paras, paragraph{
		[]string{"std/*"},
		golang.holders, bsd3.name,
		"The Go standard library and runtime, " + goversion + ".",
	})

	paths := make([]string, 0, len(mods))
	for p := range mods {
		paths = append(paths, p)
	}
	slices.Sort(paths)
	var unknown []string
	for _, p := range paths {
		m := mods[p]
		text, err := findLicence(m.Dir)
		if err != nil {
			return nil, fmt.Errorf("%s@%s: %w", p, m.Version, err)
		}
		l := splitLicence(string(text))
		i := slices.IndexFunc(filed, func(k licence) bool { return sameText(k.text, l.text) })
		if i < 0 || len(l.holders) == 0 {
			unknown = append(unknown, p+"@"+m.Version)
			continue
		}
		paras = append(paras, paragraph{
			[]string{p + "/*"},
			l.holders, filed[i].name,
			wrap("Go module "+p+", version "+m.Version+".", 76),
		})
	}
	if len(unknown) > 0 {
		return nil, fmt.Errorf("these modules' licences are not a text this file knows (Expat, or BSD-3-clause as Go words it) or name no copyright holder; "+
			"file them in internal/tools/notices/copyright.go: %s", strings.Join(unknown, ", "))
	}

	var b strings.Builder
	field(&b, "Format", dep5Format)
	field(&b, "Upstream-Name", "wopr")
	field(&b, "Upstream-Contact", repoURL+"/issues")
	field(&b, "Source", repoURL)
	field(&b, "Disclaimer", disclaimer)
	field(&b, "Comment", headerComment)
	used := map[string]bool{}
	for _, p := range paras {
		b.WriteString("\n")
		field(&b, "Files", strings.Join(p.files, "\n"))
		field(&b, "Copyright", strings.Join(p.copyright, "\n"))
		field(&b, "License", p.licence)
		if p.comment != "" {
			field(&b, "Comment", p.comment)
		}
		for _, name := range strings.Split(p.licence, " and ") {
			used[name] = true
		}
	}
	for _, l := range []licence{expat, bsd2, bsd3, mapLicence} {
		if used[l.name] {
			b.WriteString("\n")
			field(&b, "License", l.name+"\n"+l.text)
		}
	}
	return []byte(b.String()), nil
}

// field writes a DEP-5 field. Each line of value after the first goes on a continuation line, one
// space in; an empty line becomes " .", as the format asks.
func field(b *strings.Builder, name, value string) {
	for i, line := range strings.Split(value, "\n") {
		line = strings.TrimRight(line, " \t")
		switch {
		case i == 0:
			b.WriteString(name + ": " + line)
		case line == "":
			b.WriteString(" .")
		default:
			b.WriteString(" " + line)
		}
		b.WriteString("\n")
	}
}

// wrap breaks s into lines of at most width bytes at spaces; a longer word gets a line of its own.
func wrap(s string, width int) string {
	var lines []string
	line := ""
	for _, w := range strings.Fields(s) {
		switch {
		case line == "":
			line = w
		case len(line)+1+len(w) > width:
			lines = append(lines, line)
			line = w
		default:
			line += " " + w
		}
	}
	return strings.Join(append(lines, line), "\n")
}

// licenceText is a licence's copyright holders and its text without them.
type licenceText struct {
	holders []string
	text    string
}

func readLicence(path string) (licenceText, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return licenceText{}, err
	}
	l := splitLicence(string(data))
	if len(l.holders) == 0 || l.text == "" {
		return licenceText{}, fmt.Errorf("%s: no copyright line, or no licence text after it", path)
	}
	return l, nil
}

var copyrightLine = regexp.MustCompile(`(?i)^copyright\s*(?:\(c\)|©)?\s*(.+)$`)

// splitLicence separates a licence file's heading (a title such as "MIT License", the copyright
// lines and "All rights reserved.") from the licence text that follows. A licence with no
// copyright line in its heading comes back with no text.
func splitLicence(s string) licenceText {
	lines := strings.Split(strings.ReplaceAll(s, "\r\n", "\n"), "\n")
	var l licenceText
	seen := false
	i := 0
heading:
	for ; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		switch m := copyrightLine.FindStringSubmatch(t); {
		case t == "":
		case m != nil:
			l.holders = append(l.holders, m[1])
			seen = true
		case strings.EqualFold(t, "All rights reserved."):
		case !seen: // a title above the copyright lines
		default:
			break heading
		}
	}
	if !seen {
		return licenceText{}
	}
	l.text = strings.TrimRight(strings.Join(lines[i:], "\n"), "\n \t")
	return l
}

// sameText reports whether two licence texts have the same words, however they are wrapped.
func sameText(a, b string) bool {
	return strings.Join(strings.Fields(a), " ") == strings.Join(strings.Fields(b), " ")
}

// noticeTexts reads the third-party licences quoted in NOTICE.md: abs0's BSD licence, the fenced
// block that has "Redistribution and use" in it, and Matthew Thomas's terms, the one that names him.
func noticeTexts(notice string) (abs0, mapTerms licenceText, err error) {
	blocks := fencedBlocks(notice)
	for _, block := range blocks {
		switch {
		case strings.Contains(block, "Redistribution and use"):
			abs0 = splitLicence(block)
		case strings.Contains(block, "Matthew Thomas"):
			m := regexp.MustCompile(`\(C\)\s+(\d{4})\s+(Matthew Thomas)\.`).FindStringSubmatch(block)
			if m == nil {
				return abs0, mapTerms, errors.New(`the map's terms do not say "(C) <year> Matthew Thomas."`)
			}
			mapTerms = licenceText{holders: []string{m[1] + " " + m[2]}, text: strings.TrimSpace(block)}
		}
	}
	if len(abs0.holders) == 0 || abs0.text == "" {
		return abs0, mapTerms, errors.New("no fenced block holds abs0's BSD licence with its copyright line")
	}
	if mapTerms.text == "" {
		return abs0, mapTerms, errors.New("no fenced block holds Matthew Thomas's terms")
	}
	return abs0, mapTerms, nil
}

// fencedBlocks returns the contents of the Markdown code blocks fenced with ``` in s.
func fencedBlocks(s string) []string {
	var blocks []string
	var cur []string
	in := false
	for _, line := range strings.Split(strings.ReplaceAll(s, "\r\n", "\n"), "\n") {
		switch {
		case strings.HasPrefix(line, "```") && !in:
			in, cur = true, nil
		case strings.HasPrefix(line, "```"):
			in = false
			blocks = append(blocks, strings.Join(cur, "\n"))
		case in:
			cur = append(cur, line)
		}
	}
	return blocks
}

// taggedFiles lists the Go files under cmd/ and internal/, tests and test data aside, that hold
// text tagged as the film's (film or reconstructed), as abs0's transcription, or as Matthew
// Thomas's map. Paths are relative to root, with forward slashes, sorted.
func taggedFiles(root string) (film, abs0, maps []string, err error) {
	for _, dir := range []string{"cmd", "internal"} {
		err = filepath.WalkDir(filepath.Join(root, dir), func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if d.Name() == "testdata" {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			src, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			rel = filepath.ToSlash(rel)
			if filmTag.Match(src) {
				film = append(film, rel)
			}
			if abs0Tag.Match(src) {
				abs0 = append(abs0, rel)
			}
			if mapTag.Match(src) {
				maps = append(maps, rel)
			}
			return nil
		})
		if err != nil {
			return nil, nil, nil, err
		}
	}
	slices.Sort(film)
	slices.Sort(abs0)
	slices.Sort(maps)
	return film, abs0, maps, nil
}
