// Command notices generates THIRD_PARTY_NOTICES.txt: the licence of every module linked
// into wopr, plus the Go project's own licence.
//
//	go run ./internal/tools/notices            # rewrite THIRD_PARTY_NOTICES.txt
//	go run ./internal/tools/notices -check     # fail if the file is out of date
//
// MIT and BSD licences require their notices to accompany binary redistributions, so the
// file ships in every release archive and is embedded for `wopr --licenses`.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const output = "THIRD_PARTY_NOTICES.txt"

// licenceNames are tried in order in each module's root directory.
var licenceNames = []string{
	"LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "LICENCE.md", "LICENCE.txt",
	"COPYING", "COPYING.md", "COPYING.txt", "License", "license", "license.md",
}

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
	Replace *module
}

type pkg struct {
	Standard bool
	Module   *module
}

func main() {
	check := flag.Bool("check", false, "fail if "+output+" is out of date instead of rewriting it")
	pattern := flag.String("pkg", "./cmd/wopr", "package whose dependencies are listed")
	flag.Parse()
	got, err := generate(*pattern)
	if err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
	if *check {
		cur, err := os.ReadFile(output)
		if err != nil || !bytes.Equal(bytes.ReplaceAll(cur, []byte("\r\n"), []byte("\n")), got) {
			fmt.Fprintf(os.Stderr, "notices: %s is out of date; run: go run ./internal/tools/notices\n", output)
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(output, got, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func generate(pattern string) ([]byte, error) {
	cmd := exec.Command("go", "list", "-deps", "-json=Standard,Module", pattern)
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %w: %s", err, stderr.String())
	}
	mods := map[string]module{}
	dec := json.NewDecoder(bytes.NewReader(out))
	for {
		var p pkg
		if err := dec.Decode(&p); errors.Is(err, io.EOF) {
			break
		} else if err != nil {
			return nil, err
		}
		if p.Standard || p.Module == nil || p.Module.Main {
			continue
		}
		m := *p.Module
		if m.Replace != nil {
			m.Dir = m.Replace.Dir
		}
		mods[m.Path] = m
	}
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return nil, fmt.Errorf("go env GOROOT: %w", err)
	}
	goversion, err := exec.Command("go", "env", "GOVERSION").Output()
	if err != nil {
		return nil, fmt.Errorf("go env GOVERSION: %w", err)
	}
	return render(strings.TrimSpace(string(goroot)), strings.TrimSpace(string(goversion)), mods)
}

func render(goroot, goversion string, mods map[string]module) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("THIRD-PARTY NOTICES\n\n")
	b.WriteString("wopr is built with Go and links the modules below. Their licences follow, unmodified.\n")
	b.WriteString("Generated by `go run ./internal/tools/notices`; do not edit by hand.\n")

	goLicence, err := os.ReadFile(filepath.Join(goroot, "LICENSE"))
	if err != nil {
		return nil, fmt.Errorf("reading the Go licence: %w", err)
	}
	section(&b, "The Go Programming Language ("+goversion+": standard library and runtime)", goLicence)

	paths := make([]string, 0, len(mods))
	for p := range mods {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	var missing []string
	for _, p := range paths {
		m := mods[p]
		text, err := findLicence(m.Dir)
		if err != nil {
			missing = append(missing, p+"@"+m.Version)
			continue
		}
		section(&b, m.Path+" "+m.Version, text)
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("no licence file found for: %s", strings.Join(missing, ", "))
	}
	return b.Bytes(), nil
}

func findLicence(dir string) ([]byte, error) {
	if dir == "" {
		return nil, errors.New("module not downloaded")
	}
	for _, name := range licenceNames {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err == nil {
			return bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n")), nil
		}
	}
	return nil, errors.New("no licence file")
}

func section(b *bytes.Buffer, title string, text []byte) {
	b.WriteString("\n")
	b.WriteString(strings.Repeat("=", 79))
	b.WriteString("\n")
	b.WriteString(title)
	b.WriteString("\n")
	b.WriteString(strings.Repeat("=", 79))
	b.WriteString("\n\n")
	b.Write(bytes.TrimRight(text, "\n"))
	b.WriteString("\n")
}
