// Command manpage writes docs/man/wopr.6, wopr's manual page (section 6, games). It reads
// the options from internal/cli's flag table, the games from the catalog and their pages in
// site/data/games, and the scenes from internal/movie, so the page cannot drift from the
// program.
//
//	go run ./internal/tools/manpage            # rewrite docs/man/wopr.6
//	go run ./internal/tools/manpage -check     # fail if the file is out of date
//
// The page is dated by the newest release in .changes (changie's vX.Y.Z.md files), never
// by the clock, so the same tree always gives the same page. Run it from the repository
// root.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/GhostofGoes/WOPR/internal/cli"
	"github.com/GhostofGoes/WOPR/internal/games/catalog"
	"github.com/GhostofGoes/WOPR/internal/movie"
	"github.com/GhostofGoes/WOPR/internal/theme"
)

const output = "docs/man/wopr.6"

func main() {
	check := flag.Bool("check", false, "fail if "+output+" is out of date instead of rewriting it")
	flag.Parse()
	got, err := generate(".")
	if err != nil {
		fmt.Fprintln(os.Stderr, "manpage:", err)
		os.Exit(2) // could not check: not the same as out of date
	}
	if *check {
		cur, err := os.ReadFile(output)
		cur = bytes.ReplaceAll(cur, []byte("\r\n"), []byte("\n"))
		if err != nil || !bytes.Equal(cur, got) {
			fmt.Fprintf(os.Stderr, "manpage: %s is out of date; run: go run ./internal/tools/manpage\n%s", output, firstDifference(cur, got))
			os.Exit(1)
		}
		return
	}
	if err := write(output, got); err != nil {
		fmt.Fprintln(os.Stderr, "manpage:", err)
		os.Exit(1)
	}
}

func write(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

// firstDifference shows the first line where the file and the generated page part.
func firstDifference(cur, want []byte) string {
	a, b := strings.Split(string(cur), "\n"), strings.Split(string(want), "\n")
	for i := range max(len(a), len(b)) {
		var x, y string
		if i < len(a) {
			x = a[i]
		}
		if i < len(b) {
			y = b[i]
		}
		if x != y {
			return fmt.Sprintf("line %d:\n  file: %q\n  want: %q\n", i+1, x, y)
		}
	}
	return ""
}

// fallbackDate dates the page while .changes holds no release yet.
const fallbackDate = "2026-10-07"

var versionFile = regexp.MustCompile(`^v(\d+)\.(\d+)\.(\d+)\.md$`)

// release finds the newest release among changie's version files in dir and the date in
// its heading ("## v0.2.0 - 2026-10-07"). With none, the version is "".
func release(dir string) (version, date string, err error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return "", fallbackDate, nil
	}
	if err != nil {
		return "", "", err
	}
	var newest [3]int
	file := ""
	for _, e := range entries {
		m := versionFile.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		var v [3]int
		for i := range v {
			v[i], _ = strconv.Atoi(m[i+1])
		}
		if file == "" || slices.Compare(v[:], newest[:]) > 0 {
			newest, file = v, e.Name()
		}
	}
	if file == "" {
		return "", fallbackDate, nil
	}
	f, err := os.Open(filepath.Join(dir, file))
	if err != nil {
		return "", "", err
	}
	defer func() { _ = f.Close() }()
	sc := bufio.NewScanner(f)
	sc.Scan()
	d := regexp.MustCompile(`\d{4}-\d{2}-\d{2}`).FindString(sc.Text())
	if d == "" {
		return "", "", fmt.Errorf("%s: no date (YYYY-MM-DD) in its first line %q", file, sc.Text())
	}
	return fmt.Sprintf("%d.%d.%d", newest[0], newest[1], newest[2]), d, nil
}

// generate builds the page from the tree at root.
func generate(root string) ([]byte, error) {
	reg := catalog.Registry()
	gs, err := loadGames(root, reg)
	if err != nil {
		return nil, err
	}
	version, date, err := release(filepath.Join(root, ".changes"))
	if err != nil {
		return nil, err
	}
	source := "wopr"
	if version != "" {
		source += " " + version
	}
	p := page{names: names(gs)}
	p.line(`.\" wopr(6). Generated by "go run ./internal/tools/manpage" from internal/cli,`)
	p.line(`.\" internal/games/catalog, internal/movie and site/data/games. Do not edit.`)
	// The date stays unescaped, since mandoc cannot read 2026\-10\-08 as a date. groff 1.23
	// and later, without Debian's man.local, print its hyphens as U+2010 in the footer.
	p.line(fmt.Sprintf(`.TH WOPR 6 %s "%s" "Games Manual"`, date, escape(source)))
	p.leftAlign()
	writeIntro(&p)
	if err := writeOptions(&p); err != nil {
		return nil, err
	}
	writeGames(&p, gs)
	writeScenes(&p)
	writeEnd(&p)
	return []byte(p.String()), nil
}

// names are the lower-case words the page uses as names, which it never splits (see
// page.literal): the program's, and every theme, game, alias and scene, so that one added
// later is never split either.
func names(gs []game) map[string]bool {
	out := map[string]bool{"wopr": true}
	add := func(words ...string) {
		for _, w := range words {
			if !strings.Contains(w, " ") {
				out[strings.ToLower(w)] = true
			}
		}
	}
	add(theme.Names()...)
	for _, g := range gs {
		add(g.Slug)
		add(g.Aliases...)
	}
	for _, s := range movie.Scenes() {
		add(s.Slug)
	}
	return out
}

func writeIntro(p *page) {
	p.macro("SH", "NAME")
	p.line(`wopr \- the WOPR computer from WarGames (1983), in your terminal`)
	p.macro("SH", "SYNOPSIS")
	p.macro("B", "wopr")
	p.macro("RI", "[", "options", "]")
	p.macro("RI", "[", "game", "]")
	p.line(".br")
	p.macro("B", "wopr")
	p.macro("B", "--movie")
	p.macro("RB", "[", "--only", "]")
	p.macro("RI", "[", "options", "]")
	p.macro("RI", "[", "scene", "]")

	p.macro("SH", "DESCRIPTION")
	p.macro("B", "wopr")
	p.text("is a terminal recreation of the WOPR (War Operation Plan Response) computer from the 1983 film")
	p.macro("IR", "WarGames", ".")
	p.text("You dial in, find your way past the LOGON: prompt, talk to WOPR, and play the games on its list. " +
		"One of them is Global Thermonuclear War, which cannot be won.")
	p.macro("PP")
	p.text("At the LOGON: prompt, the film's backdoor still works: `Joshua`. " +
		"Once you are logged on, type `LIST GAMES` and pick a game by its name or its number on the list. " +
		"Esc twice leaves a game and goes back to WOPR. " +
		"Type `LOGOFF`, `QUIT` or `EXIT` to leave; Ctrl+C quits at any time.")
	p.macro("PP")
	p.text("A game named on the command line starts at once, without the dial, the logon and the greeting. " +
		"`wopr` needs a terminal of at least 80 columns and 24 rows, and it never uses the network.")
}

// optionDetails says more about each option than the help's one line, in page.text's markup.
// Every flag in internal/cli has an entry (TestOptionDetails).
var optionDetails = map[string]string{
	"version":  "Print the version, the commit and the build date, then exit.",
	"help":     "Print a summary of the options and exit.",
	"games":    "List the games in the order of the film's `LIST GAMES`, with the shortest name each one answers to, then exit.",
	"scenes":   "List movie mode's scenes, with their numbers and names, then exit.",
	"licenses": "Print `wopr`'s licence, <NOTICE.md>, and the licences of the third-party code built into it, then exit.",
	"play": "Start the <game> at once. A game can be named by its number on the list, its name, an alias, or the start of a name that fits only one game; GAMES below gives the shortest. " +
		"Without `--play`, a game named on the command line starts the same way: `wopr chess` is `wopr --play chess`.",
	"movie": "Replay the film's scenes at WOPR's terminal, from the scene named to the end of the film, then exit. " +
		"Without a scene, open a menu of scenes. See MOVIE SCENES below.",
	"only": "With `--movie`, play just the chosen scene, then exit. From the menu, each scene picked plays alone, then the menu returns.",
	"instant": "Show text at once instead of typing it out, and skip the animations. " +
		"Any key also finishes the line being typed.",
	"seed": "Run deterministically with the seed <n>, a whole number of 0 or more: the same seed gives the same deals, mazes and replies. " +
		"The games' searches then stop at a fixed depth. Movie mode ignores the seed.",
	"reduce-motion": "Stop the blinking, hold the front panel's lights still, and keep the ending at a steady pace. " +
		"The typing and the animations still play; `--instant` skips them.",
}

func writeOptions(p *page) error {
	p.macro("SH", "OPTIONS")
	p.text("Options can come before or after the game or scene.")
	var missing []string
	for _, f := range cli.Flags() {
		detail, ok := optionDetails[f.Long]
		if f.Long == "theme" {
			detail, ok = themeDetail(), true
		}
		if !ok {
			missing = append(missing, f.Long)
			continue
		}
		p.macro("TP")
		short, long := "`-"+f.Short+"`", "`--"+f.Long+"`"
		if f.Arg != "" {
			short, long = short+" <"+f.Arg+">", long+" <"+f.Arg+">"
		}
		p.line(p.phrase(short + ", " + long))
		p.text(detail)
		if f.Env != "" {
			p.text("The environment variable `" + f.Env + "` sets it too; the option wins.")
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("no description for option --%s in internal/tools/manpage", strings.Join(missing, ", --"))
	}
	return nil
}

func themeDetail() string {
	return fmt.Sprintf("Use the colour theme <name>: %s. The default is `%s`. The `norad` theme also shows the front panel.",
		joinAnd(bold(theme.Names()), "or"), theme.Default)
}

// bold marks up each of words in bold, for page.text.
func bold(words []string) []string {
	out := make([]string, len(words))
	for i, w := range words {
		out[i] = "`" + w + "`"
	}
	return out
}

// shellWords quotes each name that holds a space, as a shell needs it typed (wopr "noughts and
// crosses"), so that a list of names reads as the names it holds.
func shellWords(names []string) []string {
	out := make([]string, len(names))
	for i, n := range names {
		if strings.ContainsAny(n, " \t") {
			n = `"` + n + `"`
		}
		out[i] = n
	}
	return out
}

// joinAnd lists words in English: "a, b and c".
func joinAnd(words []string, and string) string {
	switch len(words) {
	case 0:
		return ""
	case 1:
		return words[0]
	}
	return strings.Join(words[:len(words)-1], ", ") + " " + and + " " + words[len(words)-1]
}

func writeGames(p *page, gs []game) {
	p.macro("SH", "GAMES")
	for _, g := range gs {
		title := g.Name
		if g.Number != nil {
			title = fmt.Sprintf("%d. %s", *g.Number, g.Name)
		}
		p.macro("SS", title)
		p.text("Start it with")
		p.macro("BR", g.Launch, ".")
		p.text("It also answers to " + joinAnd(bold(shellWords(g.Aliases)), "and") + ".")
		p.macro("PP")
		p.plain(g.Summary)
		p.macro("PP")
		p.text("How to play:")
		p.bullets(g.HowToPlay)
		p.macro("PP")
		p.text("Tips:")
		p.bullets(g.Tips[:manTips])
	}
}

func writeScenes(p *page) {
	p.macro("SH", "MOVIE SCENES")
	p.text("`wopr --movie` replays the film's scenes at WOPR's terminal, typed and paced as on screen, through the same console and games you play with. " +
		"These are the scenes, in the film's order:")
	for _, s := range movie.Scenes() {
		p.macro("TP")
		p.macro("B", fmt.Sprintf("%d %s", s.Number, s.Slug))
		p.plain(s.Blurb)
	}
	p.macro("PP")
	p.text("`wopr -m 3`, or `wopr -m first-strike`, or any start of a name that fits one scene, plays from that scene to the end, then exits. " +
		"With no scene, `wopr -m` opens a menu of the scenes. " +
		"Add `-o` (`--only`) to play just one scene. " +
		"`wopr --scenes` lists the scenes.")
	p.macro("PP")
	p.text("While a scene plays, Space pauses and resumes, `n` or Right skips to the next scene, `p` or Left goes back one, and Esc opens the menu. " +
		"Once the climax reaches tic-tac-toe, it plays to the end. " +
		"Every replay is the same: movie mode ignores `--seed` and `WOPR_SEED`.")
}

func writeEnd(p *page) {
	p.macro("SH", "EXIT STATUS")
	for _, s := range [][2]string{
		{"0", "The session ended normally: `LOGOFF`, the end of movie mode, a print-and-exit option, or SIGTERM."},
		{"1", "A runtime error or a crash."},
		{"2", "A usage error, such as an unknown option, game, scene or theme, a seed that is not a whole number, too many arguments, " +
			"options that cannot be combined, a name that fits more than one, or no terminal to run in (standard output is not a terminal, or `TERM` is `dumb`)."},
		{"130", "Ctrl+C or SIGINT."},
	} {
		p.macro("TP")
		p.macro("B", s[0])
		p.text(s[1])
	}

	p.macro("SH", "ENVIRONMENT")
	p.text("A variable that switches something on is false when it is empty or 0, false, no or off, and true otherwise.")
	for _, f := range cli.Flags() {
		if f.Env == "" {
			continue
		}
		p.macro("TP")
		p.macro("B", f.Env)
		if f.Arg == "" {
			p.text("When true, it turns on `--" + f.Long + "` (" + f.Help + ").")
		} else {
			p.text("It gives `--" + f.Long + "` its value (" + f.Help + "). Empty is the same as unset.")
		}
	}
	for _, e := range [][2]string{
		{"WOPR_PANEL", "Shows the front panel when true and hides it when false, in any theme. Unset or empty, the theme decides: `norad` shows it."},
		{"WOPR_DEBUG", "When true, `wopr` writes a debug log (never what you type) and prints its path when it exits. See FILES."},
		{"NO_COLOR", "Set to any non-empty value, it turns colour off."},
		{"TERM", "When it is `dumb`, `wopr` does not start its full-screen interface and exits with status 2; the options that print and exit still work."},
	} {
		p.macro("TP")
		p.macro("B", e[0])
		p.text(e[1])
	}

	p.macro("SH", "FILES")
	p.macro("TP")
	p.macro("I", "~/.cache/wopr/debug.log")
	p.text("The debug log that `WOPR_DEBUG` turns on. It is under <$XDG_CACHE_HOME> when that is set, and in <~/Library/Caches/wopr> on macOS.")

	p.macro("SH", "NOTES")
	p.text("`wopr` is a fan-made homage. It is not affiliated with or endorsed by the makers or owners of <WarGames>. " +
		"The code is under the MIT licence. Film quotations and third-party text are not covered by it; " +
		"`wopr --licenses` prints the licence, <NOTICE.md>, which says what they are and who they belong to, " +
		"and the licences of the third-party code built into `wopr`.")

	p.macro("SH", "BUGS")
	// The URL ends its line, with no full stop that a terminal could take as part of it.
	p.text("Report bugs in the issue tracker: " + issuesURL)
	p.macro("PP")
	p.text("Run `wopr` with `WOPR_DEBUG=1` and attach the debug log it names when it exits, with the seed if you used one. " +
		"The full-screen interface has not yet been tried with a screen reader.")

	p.macro("SH", "EXAMPLES")
	for _, ex := range [][2]string{
		{"wopr", "Dial in and log on."},
		{"wopr chess -i", "Play chess with no typewriter pacing."},
		{"wopr --games", "List the games."},
		{"wopr -m 2", "Replay the film from scene 2."},
		{"wopr -m joshua -o", "Replay just the `joshua` scene."},
		{"WOPR_THEME=green wopr -r", "Use the `green` theme, with no blinking."},
	} {
		p.macro("TP")
		p.macro("B", ex[0])
		p.text(ex[1])
	}

	p.macro("SH", "SEE ALSO")
	p.text("The guide to `wopr` and its games, with screenshots: " + siteURL)
	p.line(".br")
	p.text("The source code: " + repoURL)
}

// Where the project lives. The URLs are plain text, which every reader shows as it is, and
// like other names they are never split (see page.literal). A man(7) link, the .UR macro,
// would not help: with hyperlinks off, groff 1.23 prints the URL in angle brackets that are
// not ASCII, and mandoc's lint warns of an empty block.
const (
	siteURL   = cli.DocsURL
	repoURL   = "https://github.com/GhostofGoes/WOPR"
	issuesURL = repoURL + "/issues"
)
